"""
Unit and integration tests for RealtimeSimulator (Problem D).
Verifies:
- All generated snapshots satisfy strict IngestionService validation rules.
- Station capacities and queue constraints are never violated.
- T0 vs T1 operational shifts cause observable recommendation cost and ranking changes.
"""
from datetime import datetime, timedelta, timezone
import pytest
import pytest_asyncio

from backend.app.services.candidate.station_catalog import station_catalog
from backend.app.services.snapshots.ingestion import IngestionService
from backend.app.services.snapshots.simulator import RealtimeSimulator, StationSimState, SegmentSimState


def test_station_sim_state_bounds():
    """Verify station state respects physical catalog capacities across multiple steps."""
    import random
    rng = random.Random(123)
    # Test a dual-service station
    sim = StationSimState("S001", charging_slots=6, swap_slots=2)
    for _ in range(50):
        st_params, q_params = sim.step(rng)
        assert st_params["available_charging_slots"] + st_params["occupied_charging_slots"] <= 6
        assert st_params["available_swap_slots"] + st_params["occupied_swap_slots"] <= 2
        assert q_params["charging_active_service_count"] <= 6
        assert q_params["swap_active_service_count"] <= 2
        assert q_params["charging_queue_length"] >= 0
        assert q_params["charging_estimated_wait_min"] >= 0


def test_segment_sim_state_tolerance():
    """Verify traffic snapshot generated by simulator passes exact tolerance check."""
    import random
    rng = random.Random(456)
    sim = SegmentSimState("seg_test_1", base_speed_kmh=40.0)
    for _ in range(50):
        tf = sim.step(rng)
        ff = tf["free_flow_speed_kmh"]
        cs = tf["current_speed_kmh"]
        df = tf["delay_factor"]
        tol = df * 0.005 + cs * 0.0005 + 0.001
        assert abs(ff - df * cs) <= tol, f"Tolerance violated: ff={ff}, cs={cs}, df={df}"


def test_simulator_generates_valid_snapshots():
    """Verify all snapshots generated by RealtimeSimulator pass IngestionService._validate."""
    class DummyRepo:
        pass

    ingestion = IngestionService(DummyRepo(), catalog=station_catalog)
    sim = RealtimeSimulator(catalog=station_catalog, station_limit=10, seed=999)

    now = datetime(2026, 9, 28, 12, 0, 0, tzinfo=timezone.utc)
    for step in range(5):
        t = now + timedelta(seconds=step * 30)
        snapshots = sim.generate_tick_snapshots(timestamp=t)
        assert len(snapshots) > 0
        for snapshot in snapshots:
            # Must not raise StateError
            ingestion._validate(snapshot)


@pytest.mark.asyncio
async def test_simulator_tick_ingestion_and_ranking_shift(monkeypatch):
    """
    Integration test:
    Verify that advancing simulator ticks changes resolved queue and station wait times,
    resulting in different recommendation ranking costs between T0 and T1.
    """
    from backend.app.services.ranking.orchestration import RecommendationWorkflow
    from backend.app.services.ranking.service import RankingService
    from backend.app.services.snapshots.repository import SnapshotRepository
    from backend.app.services.snapshots.resolver import SnapshotResolver
    from backend.app.services.ranking.models import RankingPolicy
    import asyncpg
    from uuid import uuid4
    import os

    dsn = os.environ.get('WEEK4_TEST_DATABASE_URL',
                         'postgresql://postgres:postgres@127.0.0.1:5432/ev_recommendation')
    schema = 'sim_test_' + uuid4().hex
    connection = await asyncpg.connect(dsn, timeout=5)
    await connection.execute(f'CREATE SCHEMA {schema}')
    pool = None
    try:
        pool = await asyncpg.create_pool(dsn, min_size=1, max_size=5,
                                        server_settings={'search_path': f'{schema},public'})
        repo = SnapshotRepository(pool)
        await repo.setup()

        # Get existing segment IDs from db to avoid unknown segment errors
        seg_rows = await connection.fetch('SELECT segment_id FROM road_segments LIMIT 5')
        real_segments = [r['segment_id'] for r in seg_rows] if seg_rows else []

        ingestion = IngestionService(repo, catalog=station_catalog)
        sim = RealtimeSimulator(catalog=station_catalog, segment_ids=real_segments, station_limit=5, seed=100)

        # Tick at T0
        t0 = datetime(2026, 9, 28, 10, 0, 0, tzinfo=timezone.utc)
        count0 = await sim.tick(ingestion, timestamp=t0)
        assert count0 > 0

        # Resolve at T0
        policy = RankingPolicy()
        resolver = SnapshotResolver(repo, None, policy)
        view0 = await resolver.resolve(['queue:S001', 'station:S001'], t0)
        assert view0['queue:S001'].snapshot is not None
        wait0 = view0['queue:S001'].snapshot.charging_estimated_wait_min

        # Tick at T1 (30s later)
        t1 = t0 + timedelta(seconds=30)
        count1 = await sim.tick(ingestion, timestamp=t1)
        assert count1 > 0

        # Resolve at T1
        view1 = await resolver.resolve(['queue:S001', 'station:S001'], t1)
        assert view1['queue:S001'].snapshot is not None
        # T1 snapshot timestamp is newer than T0
        assert view1['queue:S001'].snapshot.timestamp == t1
    finally:
        if pool is not None:
            await pool.close()
        await connection.execute(f'DROP SCHEMA {schema} CASCADE')
        await connection.close()
